name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: SwiftPM Tests (macOS, ${{ matrix.config }})
    runs-on: macos-14
    timeout-minutes: 20
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        config: [debug, release]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select latest stable Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Show tools
        run: |
          xcodebuild -version
          swift --version

      - name: Compute Swift cache key
        id: swift
        run: |
          set -euo pipefail
          ver=$(swift --version | head -n1 | sed -E 's/.*version ([0-9.]+).*/\1/')
          echo "version=$ver" >> "$GITHUB_OUTPUT"

      - name: Cache SwiftPM
        uses: actions/cache@v4
        with:
          path: |
            .build
            ~/.swiftpm
          key: ${{ runner.os }}-swiftpm-${{ steps.swift.outputs.version }}-${{ hashFiles('Package.swift') }}
          restore-keys: |
            ${{ runner.os }}-swiftpm-${{ steps.swift.outputs.version }}-
            ${{ runner.os }}-swiftpm-

      - name: Resolve dependencies
        run: swift package resolve

      - name: Build (${{ matrix.config }})
        run: swift build -c ${{ matrix.config }}

      - name: Test (${{ matrix.config }})
        run: swift test -c ${{ matrix.config }} --parallel

